name: identity_iris

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-horizon-cosmoparrot:
    uses: ./.github/workflows/_fetch_build_push_image.yml
    with:
      source_repository: 'telekom/horizon-cosmoparrot'
      source_branch: 'wip'
      source_dockerfile: 'Dockerfile'
      target_image: 'ghcr.io/${{ github.repository_owner }}/horizon-cosmoparrot'
      target_architecture: 'linux/amd64'
      target_registry: 'ghcr.io'
      target_registry_username: ${{ github.actor }}
    secrets:
      target_registry_password: ${{ secrets.GITHUB_TOKEN }}